name: Format plist file

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  format-plist:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check original plist file
        run: |
          echo "Original plist file contents:"
          if [ -f com.apple.UIKit.plist ]; then
            plutil -convert xml1 -o - com.apple.UIKit.plist
          else
            echo "The plist file does not exist."
            exit 1
          fi

      - name: Convert binary plist to XML
        run: |
          if [ -f com.apple.UIKit.plist ]; then
            plutil -convert xml1 com.apple.UIKit.plist
            echo "Converted plist file contents:"
            cat com.apple.UIKit.plist
          else
            echo "The plist file does not exist."
            exit 1
          fi
