name: Format plist file

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  format-plist:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check original plist file
        run: |
          echo "Original plist file contents:"
          if [ -f com.apple.UIKit.plist ]; then
            plutil -convert xml1 -o - com.apple.UIKit.plist
          else
            echo "The plist file does not exist."
            exit 1
          fi

      - name: Execute Python code
        run: |
          echo "Executing Python code..."
          python3 - << 'EOF'
import plistlib
import sys

try:
    with open('com.apple.UIKit.plist', 'rb') as f:
        plist_data = plistlib.load(f)
        print(plist_data)
except Exception as e:
    print(f'Error reading plist: {e}', file=sys.stderr)
    sys.exit(1)
EOF
