name: Modify Plist File

on:
  push:
    branches:
      - main

jobs:
  modify-plist:
    runs-on: macos-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install tools
      run: |
        brew install xmlstarlet

    - name: Convert plist to XML
      run: |
        plutil -convert xml1 ./com.apple.UIKit.plist -o ./com.apple.UIKit.plist.xml

    - name: Add line to XML
      run: |
        xmlstarlet ed --inplace -s '/plist/dict' -t elem -n key -v 'UIStatusBarVisualProviderClassName' \
          -s '/plist/dict/key[text()="UIStatusBarVisualProviderClassName"]' -t elem -n string -v '_UIStatusBarVisualProvider_Split1170' \
          ./com.apple.UIKit.plist.xml

    - name: Commit and push changes
      run: |
        git config --global user.email "lardxbox2006@gmail.com"
        git config --global user.name "websitehoster-dev"
        git add ./com.apple.UIKit.plist.xml
        git commit -m "Modify UIStatusBarVisualProviderClassName in com.apple.UIKit.plist.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
